previewsEnabled: true
previewsExpireAfterDays: 2
services:
- type: web
  autoDeploy: true
  plan: starter
  ##initialDeployHook: ./dephook.sh
  ##previewPlan: free
  name: simple-sinatra-blueprint
  env: ruby
  healthCheckPath: /api/utility/health
  buildCommand: ./build.sh
  startCommand: ./run.sh
