previewsEnabled: true
#previewsExpireAfterDays: 1
services:
- type: web
  autoDeploy: true
  repo: https://github.com/mmaddex/simple-sinatra.git
  ##plan: starter plus
  initialDeployHook: ./dephook.sh
  name: simple-sinatra-or-infra
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: ./run.sh
  envVars:
    - fromGroup: auth
