previewsEnabled: true
previewsExpireAfterDays: 2
services:
- type: web
  autoDeploy: true
  plan: starter
  repo: https://github.com/Mmaddex/simple-sinatra.git
  name: simple-sinatra-blueprint
  env: ruby
  rootDir: sin
  buildCommand: ./build.sh
  startCommand: ./run.sh
