previewsEnabled: true
previewsExpireAfterDays: 2
services:
- type: web
  repo: https://github.com/mmaddex/simple-sinatra.git
  autoDeploy: true
  plan: starter
  ##initialDeployHook: ./dephook.sh
  ##previewPlan: free
  name: simple-sinatra-blueprint-separatae
  env: ruby
  healthCheckPath: /api/utility/health
  buildCommand: ./build.sh
  startCommand: ./run.sh
