services:
- type: web
  repo: https://github.com/mmaddex/simple-sinatra.git
  branch: main
  autoDeploy: true
  plan: starter
  ##initialDeployHook: ./dephook.sh
  ##previewPlan: free
  name: simple-sinatra
  env: ruby
  healthCheckPath: /health
  buildCommand: ./build.sh
  startCommand: ./run.sh
  domains:
    - www.frank.mattmaddex.com
- type: web
  env: static
  repo: https://gitlab.com/mmaddex1/jekyll.git
  autoDeploy: true
  name: static
  buildCommand: ./build.sh
  staticPublishPath: _site
  domains: 
    - static.mattmaddex.com
